conda-incubator/conda-recipe-manager

- Makefile
- conda_recipe_manager/parser/recipe_parser.py
- tests/parser/test_recipe_parser.py
- tests/test_aux_files/new_format_pytest-pep8.yaml
- tests/test_aux_files/pytest-pep8.yaml
- In some scenarios, an empty dictionary could be inserted into a part of the new `tests` section, causing an index-out-of-bounds exception. This PR addresses that issue.
- Against AnacondaRecipes, this fix increases our "success" conversion metric from 70% to 85%
- Also fixes a few `make` directives that were missing the testing directory. This got missed in upgrading the `Makefile` a few weeks back
> Fixes empty dictionary conversion bug

- .github/actions/setup-env/action.yaml
- .github/workflows/ci.yaml
- conda_recipe_manager/commands/convert.py
- conda_recipe_manager/commands/rattler_bulk_build.py
- conda_recipe_manager/parser/recipe_parser.py
- pyproject.toml
- tests/test_aux_files/integration/anaconda_recipes/types-pyyaml-feedstock/recipe/meta.yaml
- tests/test_aux_files/integration/anaconda_recipes/types-toml-feedstock/recipe/meta.yaml
- tests/test_aux_files/new_format_huggingface_hub.yaml
- tests/test_aux_files/new_format_simple-recipe.yaml
- tests/test_aux_files/new_format_types-toml.yaml
This first-pass of an integration test runs a bulk conversion operation against a few recipe files. In the future, I anticipate adding many more recipe files from various sources, to get a clear picture at how the conversion process is going.
In essence, the new integration test...
- Installs the project
- Converts all recipes in the integration test folder (1 instance per category/directory of files)
- Takes the converted recipes and performs a dry-run build using rattler-build of each recipe that has been converted.
- This does not exclude files that had errors in the conversion process. If a `recipe.yaml` exists in the test directory, it will undergo a dry-run build.
- The conversion and dry-run-build phases must pass a minimum success threshold in order to "pass"
Some notes:
- Success …
> Starts work on first integration test

- conda_recipe_manager/parser/recipe_parser.py
- tests/parser/test_recipe_parser.py
- tests/test_aux_files/google-cloud-cpp.yaml
- tests/test_aux_files/new_format_google-cloud-cpp.yaml
Fixes an illegal patch operation performed in the `test/files` -> `tests/files/recipe` transformation. You can't add a new path in the path of values you are currently replacing.
> Test files transform fix

- .github/CODEOWNERS
- .github/workflows/ci.yaml
- conda_recipe_manager/commands/conda_recipe_manager.py
- conda_recipe_manager/commands/convert.py
- conda_recipe_manager/commands/rattler_bulk_build.py
- conda_recipe_manager/commands/utils/print.py
- pyproject.toml
- recipe/meta.yaml
- tests/commands/test_conda_recipe_manager.py
- tests/commands/test_convert.py
- tests/commands/test_rattler_bulk_build.py
- tests/parser/test_recipe_parser.py
- Addresses feedback from https://github.com/conda-incubator/conda-recipe-manager/issues/19
- `convert` and `rattler-bulk-build` now execute under `conda-recipe-manager`
- Alternatively, use `crm` for short
- For example, instead of `convert recipe/meta.yaml` you now use:
`conda-recipe-manager convert recipe/meta.yaml`
- Refactors and adds missing CLI smoke tests
- Breaks-out duplicated work in the scripts into a new `commands.utils.print`
module
- `black` got an update that changes spacing between `from __future__ ...` and
the file comment that precedes it
> Refactor: Commands execute under `conda-recipe-manager` namespace

- .pre-commit-config.yaml
- .pylintrc
- conda_recipe_manager/commands/convert.py
- conda_recipe_manager/commands/utils/print.py
- conda_recipe_manager/parser/recipe_parser.py
- conda_recipe_manager/parser/recipe_parser_convert.py
- environment.yaml
Enables McCabe code complexity checks via `pylint`. Also:
- Aligns the versions of `pylint` used by `pre-commit` and the `conda-recipe-manager` environment
- Refactors `convert.py` to comply with the new setting
- Suppresses the `too-complex` rule for `recipe_parser.py`. There are 3 functions out of compliance that are crucial to parsing and rendering recipes. Most of these are recursive and contain many "return-early" paradigms.
- IMO, these are not worth addressing at this time. We have bigger fish to fry.
- Breaks `recipe_parser_convert.py` into many pieces. Each "upgrade" process is now its own function. Only one of these has a complexity score of 11 and that linting error is suppressed for now.
> Enables McCabe code-complexity checking and refactors the worst offenders

- conda_recipe_manager/parser/recipe_parser_convert.py
- tests/test_aux_files/new_format_curl.yaml
- tests/test_aux_files/new_format_google-cloud-cpp.yaml
- tests/test_aux_files/new_format_multi-output.yaml
- Addresses Issue #23
- `pip_check` is now only added to "python recipes"
- A "python recipe" is a recipe where `python` is listed as a `run` dependency. If it is included for a non-python recipe, `rattler-build` will error-out for not conforming to the schema.
- Updates unit tests.
> Fixes `pip_check` inclusion issue

- conda_recipe_manager/parser/recipe_parser.py
- conda_recipe_manager/parser/recipe_parser_convert.py
- tests/parser/test_recipe_parser_convert.py
- tests/test_aux_files/new_format_google-cloud-cpp.yaml
- Fixes an issue described in #25 that left some selectors unconditionalized.
- To address this, selectors are converted first before any other operations are performed. By doing this phase first, we ensure that the selector table points to the correct paths and no selectors are accidentally wiped by patch operations.
- Makes some minor refactoring for the sake of code clean-up.
- This does not add any new regression tests, BUT does fix existing tests to ensure that the regression is caught. The mistake was previously missed when adding those tests.
> Fixes Issue #25

- conda_recipe_manager/commands/convert.py
- conda_recipe_manager/commands/rattler_bulk_build.py
- scripts/README.md
- scripts/parse_ci_output.py
Adds a quick and dirty script for parsing-out JSON results from the CI integration test scripts
To use, download all the log files from the CI run of interest and point the script at that directory. It will parse-out all the JSON objects and aggregate the statistics into a final report, including a summary of the entire run.
Here are the current results:
```json
{
"summary": {
"test_counts": {
"anaconda_recipes_01": 2,
"bioconda_recipes_01": 2,
"bioconda_recipes_02": 2,
"bioconda_recipes_03": 2,
"bioconda_recipes_04": 2,
"conda_forge_recipes_01": 2
},
"stages": {
"recipe_conversion": {
"total_recipe_files": 11336,
"total_recipes_processed": 11336,
"total_errors": 2,
"total_warnings": 17806,
"num_recipe_exceptions": 2993,
"num_recipe_errors": 2,
"num_recipe_warnings": 8342, …
```
> Stats aggregation script

- conda_recipe_manager/commands/convert.py
- conda_recipe_manager/parser/_types.py
- conda_recipe_manager/parser/recipe_parser_convert.py
- tests/parser/test_recipe_parser_convert.py
- tests/test_aux_files/pre-processed-simple-recipe_environ.yaml
- tests/test_aux_files/simple-recipe_environ.yaml
Fixes Issue #18 by way of adding a new recipe pre-processing phase to the conversion script. 
Although this particular issue could likely be fixed in the parser, there are seemingly not _that_ many recipes that use this `environ[""]` syntax and most that do use it, use it in a very specific way. I anticipate we will run into nastier problems that may require a pre-processing step, so this is at least a good candidate issue to test the waters.
> Fixes Issue #18 by adding a new conversion pre-processor

- Makefile
- conda_recipe_manager/commands/convert.py
- conda_recipe_manager/parser/recipe_parser_convert.py
- tests/parser/test_recipe_parser_convert.py
Adds a `--debug` (and `-d`) flag to the conversion script. This flag prints debugging output to `STDERR`. For now it prints the initial parse-tree and the post-conversion parse-tree. 
I've been using this strategy informally for months to determine if a bug is caused by an incorrect parse tree or a failure of the rendering function.
This PR also raises the unit testing coverage minimum to 80%. This should have been raised when the project was ported to conda-incubator.
Here's a sample debug output of a parser instance:
```
--------------------
RecipeParser Instance
- Variables Table:
{
"name": "boto",
"version": "2.49.0"
}
- Selectors Table:
[py2k]
- asadmin -h -> /test/commands/0
- taskadmin -h -> /test/commands/2
- is_modified?: False
- Tree:
/
|- package
|- name
|- {{ name|lower }}
|- …
```
> Adds `--debug` flag to conversion script

- conda_recipe_manager/parser/recipe_parser.py
- tests/parser/test_recipe_parser_convert.py
- tests/test_aux_files/boto.yaml
- tests/test_aux_files/new_format_boto.yaml
Fixes indentation edge case with lists under a collection element node.
Here's the example that caused this discovery (annotated with the correct answer):
```yaml
- script:
- if: py2k
then: asadmin -h
- s3put -h  # Incorrect
- s3put -h  # Correct
- if: py2k
then: taskadmin -h
```
This improper indentation causes an issue when `rattler-build` executes a dry-run on the recipe:
```
╭─ Finding outputs from recipe
│
╰─────────────────── (took 0 seconds)
Error:   × Parsing: failed to parse YAML: while parsing a block mapping, did not find expected key
╭─[34:7]
33 │         then: asadmin -h
34 │     - s3put -h
·       ────┬───
·           ╰── here
35 │       - if: py2k
╰────
```
Also adds a regression test to catch this issue if it happens again.
> Fixes indentation edge case with lists under a collection element node

- conda_recipe_manager/parser/_types.py
- conda_recipe_manager/parser/recipe_parser_convert.py
- tests/parser/test_recipe_parser_convert.py
- tests/test_aux_files/cctools-ld64.yaml
- tests/test_aux_files/new_format_boto.yaml
- tests/test_aux_files/new_format_cctools-ld64.yaml
- tests/test_aux_files/new_format_pytest-pep8.yaml
Fixes #47, #48, and #51 , which are all small changes. After reading through the integration testing logs, I noticed we were missing these easy transformations.
This PR also adds a new transformation function for the `source` section and sorts the `source` section keys.
> Addresses #47, #48, and #51

- .github/workflows/integration_tests.yaml
- conda_recipe_manager/parser/recipe_parser_convert.py
- tests/test_aux_files/v1_format/v1_cctools-ld64.yaml
- tests/test_aux_files/v1_format/v1_huggingface_hub.yaml
A few quick bug fixes I found and fixed today.
Also includes some minor spelling corrections that happen on occasion. They don't happen a lot but it's weird they happen more than once.
Also fixes an issue where the integration tests may silently fail to meet the testing threshold. The `pipefail` shell option was not enabled, causing `tee` to always return `0`
> Quick bug fixes

- conda_recipe_manager/commands/rattler_bulk_build.py
- conda_recipe_manager/parser/_types.py
- conda_recipe_manager/parser/recipe_parser_convert.py
- tests/parser/test_recipe_parser_convert.py
- tests/test_aux_files/regression_jinja_sub.yaml
- tests/test_aux_files/v1_format/v1_regression_jinja_sub.yaml
I found some scenarios where the JINJA substitution upgrades can fail and cause doubling up of the dollar sign (i.e. `$${{ foo }}` is added to the file instead of `${{ foo }}`.
This PR addresses those issues and adds regression tests to prevent this from happening again.
Also:
- Adds some new debug logging options to `rattler-bulk-build`
- Adds some simple license corrections to the SPDX format
> JINJA substitution fixes

- conda_recipe_manager/parser/_types.py
- conda_recipe_manager/parser/recipe_parser.py
- conda_recipe_manager/parser/recipe_parser_convert.py
- recipe/meta.yaml
- tests/parser/test_recipe_parser_convert.py
- tests/test_aux_files/simple-recipe_test_patch_add.yaml
- tests/test_aux_files/v1_format/v1_multi-output.yaml
Found some small missing build section transformations. These missing transforms are occasionally seen in R packages and should help improve compatibility with `rattler-build`.
Also:
- Improves the deprecated field system
- Creating a new function that standardizes how we handle deprecated fields
- Provides the user a warning when a deprecated field has been removed.
- No longer emits empty `context` objects
> Adds missing build transforms

- conda_recipe_manager/parser/recipe_parser_convert.py
- Spelling mistakes are now checked at every package entry point, not just at the "root" level
- Adds a few more spelling corrections
- `pip check` logic now checks for some less common `pip check` usages (like `python -m pip check`)
- Adds missing transforms for the new `/build/prefix_detection` object
> `pip check` improvements, more missing transforms, and some spelling enhancements

- .github/workflows/integration_tests.yaml
- conda_recipe_manager/parser/recipe_parser_convert.py
- tests/parser/test_recipe_parser_convert.py
- tests/test_aux_files/git-src.yaml
- tests/test_aux_files/v1_format/v1_git-src.yaml
Adds transformations for `git_url` and other fields that were previously missing. Also adds corresponding unit tests.
> Adds missing transforms for "git source" fields

- conda_recipe_manager/parser/_types.py
- conda_recipe_manager/parser/recipe_parser_convert.py
- tests/parser/test_recipe_parser_convert.py
- tests/test_aux_files/pre_processor/pp_quoted_multiline_str.yaml
- tests/test_aux_files/quoted_multiline_str.yaml
A handful of recipes have quoted multiline strings, that the parser does not support:
```yaml
description: "Tests handling of\nmultiline quoted strings"
```
So the preprocessing phase will now attempt to convert this to a pipe-marked multiline string:
```yaml
description: |
Tests handling of
multiline quoted strings
```
There aren't many recipes that use this format, and even fewer that have multiple newlines in the quoted string. Hence why this is a pre-processor fix.
> Upgrades basic quoted multiline strings

- .github/workflows/integration_tests.yaml
Adds environment configurations that many recipes rely on. This addresses #74 with a workaround.
This should give us more reliable recipe validation statistics. These environment settings do not reflect on how well `conda-recipe-manager` converts recipe files.
> Adds common environment settings

- .github/workflows/integration_tests.yaml
- conda_recipe_manager/parser/_types.py
- conda_recipe_manager/parser/recipe_parser.py
- conda_recipe_manager/parser/recipe_parser_convert.py
- tests/test_aux_files/v1_format/v1_google-cloud-cpp.yaml
[rattler-build@0.18.0](https://github.com/prefix-dev/rattler-build/releases/tag/v0.18.0) introduces a new check for the deprecated `min_pin`/`max_pin` arguments used in a number of JINJA pinning functions.
This simple regex replaces the terms with the new nomenclature, fixing the underlying issue.
In making this simple replacement, however, the integration tests started failing for the `bioconda_recipes_02` data set. Diving deeper uncovered that `yaml.dump()` enforces a strict 80-character line limit by default, causing a number of unexpected issues when converting recipes. Fixing that greatly improved compatibility with all bioconda datasets, as many bioconda recipes exceed 80 characters in length on at least 1 line.
> Fixes integration tests from rattler-build 0.18.0 update

- CHANGELOG.md
- pyproject.toml
Minor bug fixes and documentation improvements. Conversion compatibility with Bioconda recipe has improved significantly.
Includes many previously missing recipe transformations.
- Fixes integration tests from rattler-build 0.18.0 update (#76)
- Adds common environment settings (#75)
- Adds demo day intro slidedeck to CRM (#73)
- Upgrades basic quoted multiline strings (#72)
- Adds missing transforms for "git source" fields (#71)
- pip check improvements, more missing transforms, and some spelling enhancements (#70)
- Multiline summary fix issue 44 (#68)
- Preprocessor: Replace dot with bar functions (#67)
- Corrects using hash_type as a JINJA variable for the sha256 key (#66)
- Adds script_env support (#65)
- Adds missing build transforms (#62)
- Some minor improvements (#61)
> v0.2.1 Release, see CHANGELOG.md

- conda_recipe_manager/parser/_types.py
- conda_recipe_manager/parser/_utils.py
- conda_recipe_manager/parser/recipe_parser_convert.py
- tests/parser/test_recipe_parser_convert.py
- tests/test_aux_files/selector-match-upgrades.yaml
- tests/test_aux_files/v1_format/v1_boto.yaml
- tests/test_aux_files/v1_format/v1_git-src.yaml
- tests/test_aux_files/v1_format/v1_huggingface_hub.yaml
- tests/test_aux_files/v1_format/v1_non_marked_multiline_summary.yaml
- tests/test_aux_files/v1_format/v1_script-env.yaml
- tests/test_aux_files/v1_format/v1_selector-match-upgrades.yaml
- tests/test_aux_files/v1_format/v1_simple-recipe.yaml
- tests/test_aux_files/v1_format/v1_types-toml.yaml
This discovery came out of developing #77 and some discussions held on the public Conda Build Tools Element channel.
The commonly used `py<37` selector expression is no longer supported in the new recipe format (see https://github.com/conda/ceps/pull/71 and https://prefix-dev.github.io/rattler-build/latest/selectors/#selector-evaluation).
These selector aliases/expressions have been superseded by the new `match()` function in the V1 recipe format.
This is the first issue we have found that occurs in when performing a full build with `rattler-build` BUT does not appear in a dry-run build. There are likely many more such issues to be discovered.
This PR also stores `/build/skip` expressions as a single value instead of a list. I believe this was a temporary workaround to a schema issue that …
> Upgrades commonly used selectors

- .pre-commit-config.yaml
- conda_recipe_manager/parser/recipe_parser.py
- conda_recipe_manager/parser/types.py
- conda_recipe_manager/types.py
- environment.yaml
- Fixes pylint rule changes for Python 3.12. These fixes should be backwards compatible to 3.11 as well.
- Removes strict Python 3.11 requirement in pre-commit to prevent future confusion
- Updates various pre-commit plugins
- For more context, see here: https://github.com/pylint-dev/pylint/pull/9152
> Fixes pylint compatibility issues

- conda_recipe_manager/commands/convert.py
- conda_recipe_manager/parser/_types.py
- conda_recipe_manager/parser/_utils.py
- conda_recipe_manager/parser/enums.py
- conda_recipe_manager/parser/recipe_parser.py
- conda_recipe_manager/parser/recipe_parser_convert.py
- conda_recipe_manager/parser/types.py
- tests/commands/test_convert.py
- tests/parser/test_recipe_parser.py
- tests/test_aux_files/simple-recipe_to_str.out
- tests/test_aux_files/v1_format/v1_simple-recipe_to_str.out
It has occurred to me that it shouldn't take a lot of work to make the recipe parser capable of editing both V0 and V1 recipe files. You can already make some modifications to V1 recipe files, but this is untested and there will be bugs.
This is the first PR of many that will allow us to edit both V0 and V1 recipes programmatically. The parser is now able to detect which format of a recipe it has been given. Using that knowledge, it will branch on logic that is version specific.
To start, this PR fixes logic around JINJA variable management and starts adding unit test coverage for V1 recipes.
This unit test coverage is not extensive, but I wanted to break this work into multiple PRs before it got too big.
> Adds some basic support for editing V1 recipe files

- conda_recipe_manager/commands/convert.py
- conda_recipe_manager/commands/rattler_bulk_build.py
- conda_recipe_manager/commands/utils/print.py
- conda_recipe_manager/commands/utils/types.py
- conda_recipe_manager/parser/recipe_parser.py
- conda_recipe_manager/parser/recipe_parser_convert.py
- conda_recipe_manager/parser/types.py
- conda_recipe_manager/types.py
- tests/parser/test_recipe_parser.py
- tests/parser/test_recipe_parser_convert.py
These are good ideas that have been cherry-picked from more experimental branches.
- V* recipe file name constants are now centralized
- Messaging classes are now available in a more generic module. They are no longer in the `parser` module
- Error code management for CLI commands are now centralized
- `rattler-bulk-build` now requires a directory to be passed-in
- The `RecipeParser` class now provides the ability to generate a SHA-256 hash of the recipe's contents
> Minor Quality of Life improvements

- .pre-commit-config.yaml
Having pre-commit run make test and make test-cov is redundant. Running test coverage inherently runs all the tests.
> Improves test performance

- conda_recipe_manager/commands/graph.py
- Adds a missing help menu string
- `graph` now uses the same `ExitCode` enumerations that the other commands use.
> Adds minor QOL improvements to `crm graph`

- tests/file_mocking.py
This module provides tools to mock writing to a single file.
This work is based on the suggestions from this StackOverflow post: https://stackoverflow.com/questions/70861340/how-to-check-what-was-written-to-a-mock-open-fake-file
Here is some pseudo code to illustrate how to use this work:
```
from unittest import mock
from tests.file_mocking import MockWriter
mock_opener, mock_writer = MockWriter.setup_file_mockers("Mocked file contents")
with mock.patch('<function that calls to write()>', mock_opener) as f:
<call to function that writes to file>
assert str(mock_writer) == expected
```
> Adds file mocking module

- conda_recipe_manager/parser/_types.py
- conda_recipe_manager/parser/recipe_reader.py
- tests/parser/test_recipe_parser_deps.py
- tests/parser/test_recipe_reader.py
- tests/test_aux_files/sub_vars.yaml
- tests/test_aux_files/v1_format/v1_sub_vars.yaml
- Adds support for the access operator (on strings) and the `upper` JINJA
function
- Fixes several issues with JINJA variable subsitutions
- General code clean-up
- Updates tests with improvements
> `RecipeReader::get_value()` can now sub vars in strings

- conda_recipe_manager/fetcher/artifact_fetcher.py
- conda_recipe_manager/fetcher/exceptions.py
- conda_recipe_manager/parser/recipe_reader.py
- conda_recipe_manager/utils/typing.py
- tests/fetcher/test_artifact_fetcher.py
- tests/parser/test_recipe_reader.py
- tests/test_aux_files/fake_source.yaml
- tests/test_aux_files/v1_format/v1_fake_source.yaml
- tests/utils/test_typing.py
- Adds unit testing
- Includes a new `get_recipe_name()` convenience function to standardize the answering of the "what to call a recipe" problem
- Includes a simple `optional_str()` utility that forces string-evaluation unless a value is `None`.
> Completes the first iteration of `from_recipe()`

- tests/commands/test_convert.py
- tests/fetcher/test_artifact_fetcher.py
- tests/fetcher/test_http_artifact_fetcher.py
- tests/file_loading.py
- tests/grapher/test_recipe_graph_from_disk.py
- tests/http_mocking.py
- tests/utils/cryptography/test_hashing.py
Fixes #151 by deprecating the global `TEST_FILE_PATHS` constant in favor of a function that generates the same `Path` object.
Although this is a more expensive approach, it does mean that every test has the conveniences offered by `pathlib` without having to worry about how the `Path` object is constructed. 
In other words:
Calling `get_test_path()` will create an object instance that refers to either the real or the fake file system, depending on the inclusion of the `fs` fixture.
> Addresses nuance with pyfakefs and pathlib

- .pre-commit-config.yaml
- environment.yaml
Defaults now includes newer versions of the two packages we were relying on `conda-forge` for.
Some say this will fix a rare issue and that code is non-deterministic. All we know is he's called _The Stig_.
> Removes conda-forge channel

- tests/test_types.py
Resolves #177 
The new unit test aims to cover all of the methods contained in the [`MessageTable` class in `types.py`](https://github.com/conda-incubator/conda-recipe-manager/blob/main/conda_recipe_manager/types.py#L84-L159), which includes `add_message()`, `get_messages()`, `get_message_count()`, `get_totals_message()`, and `clear_messages()`.
> Test the `MessageTable` class

- conda_recipe_manager/parser/dependency.py
- conda_recipe_manager/parser/recipe_parser_deps.py
- conda_recipe_manager/parser/recipe_reader_deps.py
- tests/parser/test_dependency.py
- tests/parser/test_recipe_parser_deps.py
- tests/parser/test_recipe_reader.py
- tests/test_aux_files/h5py.yaml
Fixes a bug when dealing with certain complex dependency listings. This was discovered by some customer testing of an internal prototype. PR also adds regression tests.
> Fixes `numpy {{numpy}}` dependency bug

- .github/workflows/commit_checks.yaml
- .pre-commit-config.yaml
- .pytest.ini
- Makefile
This PR makes a handful of minor CI improvements:
- Shows the `pytest` coverage logs in the pre-commit CI test to show current code coverage. This is done in such a way that any `pre-commit` command should show the test coverage report.
- Pytest warnings are now treated as errors so that we will know about warnings sooner (through CI failures)
- Minor documentation improvements in the `Makefile`
- Removes Python `3.11` from the test matrix, as `3.11` is used by the `pre-commit` job. In other words, we are now saving some redudant computation.
This also suppresses some new warnings I found while working on this issue. Issues #236 and #237 have been created as  a result.
I ended up NOT adding `python 3.13` tests to the test matrix as it does not appear to be ready yet.
> Minor CI Improvements

- conda_recipe_manager/commands/bump_recipe.py
- conda_recipe_manager/parser/recipe_reader.py
- tests/commands/test_bump_recipe.py
- tests/test_aux_files/bump_recipe/build_num_added.yaml
- tests/test_aux_files/bump_recipe/no_build_key.yaml
This PR adds the logic to set the `/build/number` back to 0 when `bump-recipe` command is run without any flags:
`crm bump-recipe <file.yaml>`
TODO:
> Add "Set the `/build/number` back to 0" logic to bump-recipe

- .pytest.ini
- conda_recipe_manager/commands/bump_recipe.py
- conda_recipe_manager/commands/utils/types.py
- conda_recipe_manager/fetcher/artifact_fetcher.py
- environment.yaml
- recipe/meta.yaml
- tests/commands/test_bump_recipe.py
- tests/fetcher/test_artifact_fetcher.py
- tests/test_aux_files/bump_recipe/types-toml_build_num_1.yaml
- tests/test_aux_files/bump_recipe/types-toml_version_bump.yaml
- tests/test_aux_files/types-toml_src_lst.yaml
- tests/test_aux_files/v1_format/v1_types-toml_src_lst.yaml
- `bump-recipe` now supports changing the SHA-256 hash of recipe files
- This feature will not work as expected until the `version` is updated, which is tracked in #147 
- Adds `pytest-socket` as a test dependency to ensure our automated unit tests do not reach out to the network and spam legitimate URLs.
- Expands unit testing
> 169 Calculate and Change the SHA-256 hash for http/https Artifacts

- conda_recipe_manager/commands/bump_recipe.py
- tests/commands/test_bump_recipe.py
- tests/test_aux_files/bump_recipe/types-toml_version_bump.yaml
This is the remaining portion of the work for #168 . This completes the first-pass implementation of updating the version field.
This will not cover all edge cases, but should cover most simple Python-only recipe cases.
> 168 [Remaining portion]: Change the references of the old version to the new version

- Makefile
- conda_recipe_manager/commands/bump_recipe.py
- conda_recipe_manager/commands/conda_recipe_manager.py
- tests/commands/test_bump_recipe.py
- Adds support for the `logging` module for CRM commands
- `bump-recipe` now uses the `logging` module
- Adds new logged messages
- For commands that support logging, verbose logging can be enabled by: `crm -v <command>`
> 242 Use the logger in `bump-recipe`

- conda_recipe_manager/commands/bump_recipe.py
- tests/commands/test_bump_recipe.py
- tests/test_aux_files/bump_recipe/pytest-pep8_version_bump.yaml
Fixes #252 
- Recipes that contain a variable called `sha256`, `hash`, and other similar values that use that value in the `/source/sha256` for single-sourced recipe files will now update correctly. This is by far the most common case when a "hash variable" is defined.
- Lays the ground work for #255 
- Minor refactoring/reoganization
- Fixes test that was wrong until this feature was complete
> 252 Add `sha256` variable support for `bump-recipe`

- conda_recipe_manager/commands/bump_recipe.py
- conda_recipe_manager/parser/recipe_parser.py
- conda_recipe_manager/parser/recipe_parser_convert.py
- tests/commands/test_bump_recipe.py
- tests/test_aux_files/bump_recipe/types-toml_hash_type_build_num_1.yaml
- tests/test_aux_files/bump_recipe/types-toml_hash_type_version_bump.yaml
- tests/test_aux_files/types-toml_hash_type.yaml
- `bump-recipe` can now handle recipe files that use `hash_type` as a variable for the `/source/sha256` key
- Refactors some existing recipe conversion work to be leveraged in the `bump-recipe` command
- Adds unit tests
> 255 Add cleanup function to get rid of hash type usage

- conda_recipe_manager/parser/_types.py
- conda_recipe_manager/parser/recipe_parser.py
- conda_recipe_manager/parser/recipe_parser_convert.py
Minor refactoring caused by investigate #234
The more I think about this ask, the more I think we should not do it for the sake of the user. I don't think sorting keys is as important as leaving comments in place.
> 234 refactor canonical sorting work found in the recipeparserconvert class

- conda_recipe_manager/commands/bump_recipe.py
- conda_recipe_manager/commands/conda_recipe_manager.py
- conda_recipe_manager/commands/utils/types.py
- conda_recipe_manager/fetcher/base_artifact_fetcher.py
- tests/commands/test_bump_recipe.py
- tests/test_aux_files/bump_recipe/types-toml_bad_url.yaml
- tests/test_aux_files/bump_recipe/types-toml_bad_url_hash_var.yaml
- tests/test_aux_files/bump_recipe/types-toml_bad_url_multi_source.yaml
Addresses #243 
`bump-recipe` now implements a retry mechanism when fetching HTTP artifacts, improving resilience.
Also improves:
- Logging
- Error messaging
- Code complexity in `_update_sha256()`
- Back-off interval can be customized by the `-i` flag
> 243 Develop a retry mechanism for fetching artifacts in `bump-recipe`

- conda_recipe_manager/commands/bump_recipe.py
- tests/commands/test_bump_recipe.py
We now use futures to download multiple source files concurrently.
Also introduces a `--dry-run` mode that dumps the recipe file to STDOUT instead of overwriting the recipe file.
~~Putting this PR up as a Draft until I can figure out why some of the `bump_recipe_cli` tests are significantly slower after this change (causing the tests to take 4 seconds to 35 seconds).~~ That issue is now tracked in #265 as it appears to have no known user impact and is tied to the test environment.
> 260 Parallelize multiple source fetch requests

- README.md
- conda_recipe_manager/commands/README.md
Adds missing documentation regarding `bump-recipe`. Closes #268
> Adds missing bump-recipe documentation

- conda_recipe_manager/commands/bump_recipe.py
- tests/commands/test_bump_recipe.py
- tests/test_aux_files/bump_recipe/types-toml_bad_url_partial_save.yaml
Adds a new `--save-on-failure` flag to `crm bump-recipe` to allow the tool to save partially upgraded files, in the event of an unrecoverable failure.
Also simplifies adding future flags by introducing a `_CliArgs` struct to easily pass new flags into all necessary functions going forward.
> 244 bump recipe should exit and save gracefully on some failures

- environment.yaml
`pytest-socket` is now widely available on both `conda-forge` and `defaults`, allowing us to make this change.
> `conda-forge::` removed from environment.yaml

- conda_recipe_manager/parser/recipe_parser_convert.py
- conda_recipe_manager/parser/recipe_reader.py
- tests/parser/test_recipe_parser_convert.py
- tests/parser/test_recipe_reader.py
- tests/test_aux_files/issue_289_regression.yaml
- tests/test_aux_files/min_max_pin.yaml
- tests/test_aux_files/pre_processor/pp_min_max_pin.yaml
- tests/test_aux_files/v1_format/v1_issue_289_regression.yaml
- Fixes #289 by adjusting logic in `RecipeReader::is_python_recipe()`
- Adds a regression test for #289
- Adds a missing test for upgrading to newer `upper/lower` bound syntax.
> Addresses #289

- conda_recipe_manager/commands/conda_recipe_manager.py
Use `click`'s built in `@click.version_option()` decorator to add the `--version` flag.
> Add `--version` flag to crm

- conda_recipe_manager/commands/README.md
CEPS now have leading zeros:  cep-14.md => cep-0014.md.  This fixes the link.
> Fixed link to cep-0014.md (from cep-14.md)

- README.md
- tests/commands/test_bump_recipe.py
- Adds a retry flag to the slow test to mitigate the slow down described by Issue #265. Special thanks to @mrbean-bremen for suggesting this.
- Adds discovery documentation to highlight why we are doing this.
> Mitigates the test slow down described by #265

- conda_recipe_manager/parser/_types.py
- conda_recipe_manager/parser/recipe_reader.py
- tests/parser/test_recipe_reader.py
- tests/test_aux_files/sub_vars.yaml
- tests/test_aux_files/v1_format/v1_sub_vars.yaml
Fixes #321
As a bonus, the parser can now evaluate `.replace()`, `.upper()`, and `.lower()`.
This should greatly increase accuracy when evaluating source URLs in recipe files.
> Adds parser support for `| replace` evaluation

- conda_recipe_manager/parser/_types.py
- conda_recipe_manager/parser/recipe_reader.py
- tests/parser/test_recipe_reader.py
- tests/test_aux_files/sub_vars.yaml
- tests/test_aux_files/v1_format/v1_sub_vars.yaml
- Adds some initial support for `join` and `split` statements.
- Also allows for Python-style negative indexing. This is rare but does happen in recipe files.
> Some more JINJA variable support improvements
